[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://tone-craft.netlify.app/*"
  to = "https://conveybot.in/:splat"
  status = 301
  force = true
